<?php

declare(strict_types=1);

namespace Zoosper\AdminGrid;

/**
 * Renders CSRF-bearing POST controls for Grid workspace persistence.
 *
 * The host controller supplies the token generated by its existing CSRF layer.
 * User identity and Grid identity are intentionally absent from emitted fields.
 */
final readonly class GridWorkspaceMutationFormsRenderer
{
    public function render(
        GridViewState $state,
        string $actionPath,
        string $csrfField,
        string $csrfToken,
    ): string {
        $this->assertLocalPath($actionPath);
        if (trim($csrfField) === '' || trim($csrfToken) === '') {
            throw new \InvalidArgumentException(
                'Grid workspace mutation forms require a CSRF field and token.',
            );
        }

        $html = '<div class="grid-workspace__mutations" data-grid-mutations>';
        $html .= $this->saveColumnsForm($state, $actionPath, $csrfField, $csrfToken);
        $html .= $this->resetColumnsForm($actionPath, $csrfField, $csrfToken);
        $html .= $this->saveViewForm($state, $actionPath, $csrfField, $csrfToken, false);
        $html .= $this->saveViewForm($state, $actionPath, $csrfField, $csrfToken, true);

        if ($state->activeBookmarkId !== null) {
            $html .= $this->deleteViewForm(
                $state->activeBookmarkId,
                $actionPath,
                $csrfField,
                $csrfToken,
            );
        }

        return $html . '</div>';
    }

    private function saveColumnsForm(
        GridViewState $state,
        string $path,
        string $csrfField,
        string $csrfToken,
    ): string {
        $html = $this->openForm($path, GridWorkspaceMutationContract::SAVE_COLUMNS, $csrfField, $csrfToken);
        foreach ($state->visibleColumns as $key) {
            $html .= $this->hidden('visible_columns[]', $key);
        }
        foreach ($state->columnOrder as $key) {
            $html .= $this->hidden('column_order[]', $key);
        }

        return $html . '<button type="submit">Save columns</button></form>';
    }

    private function resetColumnsForm(
        string $path,
        string $csrfField,
        string $csrfToken,
    ): string {
        return $this->openForm(
            $path,
            GridWorkspaceMutationContract::RESET_COLUMNS,
            $csrfField,
            $csrfToken,
        ) . '<button type="submit">Reset columns</button></form>';
    }

    private function saveViewForm(
        GridViewState $state,
        string $path,
        string $csrfField,
        string $csrfToken,
        bool $asDefault,
    ): string {
        $action = $asDefault
            ? GridWorkspaceMutationContract::SET_DEFAULT_VIEW
            : GridWorkspaceMutationContract::SAVE_VIEW;
        $html = $this->openForm($path, $action, $csrfField, $csrfToken);
        $html .= '<label>View name <input name="view_name" maxlength="120" required></label>';
        foreach ($state->criteria->filters as $key => $value) {
            foreach (is_array($value) ? $value : [$value] as $item) {
                $html .= $this->hidden('filters[' . $key . '][]', (string) $item);
            }
        }
        $html .= $this->hidden('sort_by', (string) ($state->criteria->sortBy ?? ''));
        $html .= $this->hidden('sort_dir', $state->criteria->sortDir);
        $html .= $this->hidden('page_size', (string) $state->criteria->pager->pageSize);
        foreach ($state->visibleColumns as $key) {
            $html .= $this->hidden('visible_columns[]', $key);
        }
        foreach ($state->columnOrder as $key) {
            $html .= $this->hidden('column_order[]', $key);
        }
        $label = $asDefault ? 'Save as default view' : 'Save view';

        return $html . '<button type="submit">' . $label . '</button></form>';
    }

    private function deleteViewForm(
        int $bookmarkId,
        string $path,
        string $csrfField,
        string $csrfToken,
    ): string {
        return $this->openForm(
            $path,
            GridWorkspaceMutationContract::DELETE_VIEW,
            $csrfField,
            $csrfToken,
        ) . $this->hidden('bookmark_id', (string) $bookmarkId)
            . '<button type="submit">Delete view</button></form>';
    }

    private function openForm(
        string $path,
        string $action,
        string $csrfField,
        string $csrfToken,
    ): string {
        return '<form method="post" action="' . $this->escape($path) . '">' 
            . $this->hidden($csrfField, $csrfToken)
            . $this->hidden('action', $action);
    }

    private function hidden(string $name, string $value): string
    {
        return '<input type="hidden" name="' . $this->escape($name)
            . '" value="' . $this->escape($value) . '">';
    }

    private function assertLocalPath(string $path): void
    {
        if ($path === '' || $path[0] !== '/' || str_contains($path, '://')) {
            throw new \InvalidArgumentException(
                'Grid workspace form action must use an application-local path.',
            );
        }
    }

    private function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
