import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import {JSDOM} from 'jsdom';
const auditSource=await readFile(new URL('../../resources/admin/js/audit-log-workspace.js',import.meta.url),'utf8');
const loginSource=await readFile(new URL('../../resources/admin/js/login-history-workspace.js',import.meta.url),'utf8');
const boot=(kind)=>{const audit=kind==='audit';const cells=audit?'<td data-grid-column="actor_email">a@example.test</td><td data-grid-column="action">page.updated</td><td data-grid-column="entity_type">page</td><td data-grid-column="summary">Updated</td>':'<td data-grid-column="email">a@example.test</td><td data-grid-column="status">success</td><td data-grid-column="ip_address">127.0.0.1</td>';const html=`<section class="${audit?'audit-log-index':'login-history-index'}"><div data-grid-workspace><div class="grid-compact-actions"></div><form data-grid-filter-form><label>Query <input name="q"></label><input name="page" value="3"></form></div><table class="grid-table"><tbody><tr>${cells}</tr></tbody></table><div>Showing 1 item</div><nav class="grid-workspace__navigation"><a rel="prev">Previous</a><div class="grid-pagination-controls"><a rel="next">Next</a></div></nav></section>`;const dom=new JSDOM(html,{runScripts:'outside-only'});const form=dom.window.document.querySelector('[data-grid-filter-form]');form.requestSubmit=()=>{form.dataset.submitted='true';};dom.window.eval(audit?auditSource:loginSource);return dom;};
test('promotes Audit search composes pagination and enhances rows',()=>{const {window}=boot('audit'),d=window.document,q=d.querySelector('[name="q"]'),form=d.querySelector('[data-grid-filter-form]');assert.equal(q.type,'search');assert.equal(q.placeholder,'Search action, actor or summary');q.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.equal(d.querySelector('[name="page"]').value,'1');assert.equal(form.dataset.submitted,'true');assert.ok(d.querySelector('[data-audit-log-pagination]'));assert.equal(d.querySelector('tr').dataset.auditLogRowEnhanced,'true');assert.equal(d.querySelector('[data-grid-column="action"]').title,'page.updated');});
test('enhances Login History rows with declared status presentation',()=>{const d=boot('login').window.document,row=d.querySelector('tr'),status=d.querySelector('[data-grid-column="status"] span');assert.equal(d.querySelector('.login-history-index').dataset.loginHistoryEnhanced,'true');assert.equal(row.dataset.loginHistoryRowEnhanced,'true');assert.equal(status.classList.contains('login-history-index__status--success'),true);assert.equal(status.title,'success');assert.ok(d.querySelector('[data-login-history-pagination]'));});
