<?php

declare(strict_types=1);

return [[
    'id' => 'system.admin',
    'label' => 'Administration',
    'category' => 'advanced',
    'description' => 'Core administration behaviour and paths.',
    'permission' => 'settings.manage',
    'sort_order' => 900,
    'groups' => [[
        'id' => 'interface',
        'label' => 'Interface',
        'description' => 'Settings catalogue display preferences.',
        'sort_order' => 100,
        'open_by_default' => true,
        'settings' => [[
            'path' => 'settings.catalogue.show_paths',
            'label' => 'Show configuration paths',
            'type' => 'boolean',
            'description' => 'Display technical configuration paths in the Settings catalogue.',
            'default' => true,
            'sort_order' => 100,
        ]],
    ], [
        'id' => 'security',
        'label' => 'Security',
        'description' => 'Environment-controlled Admin session security.',
        'sort_order' => 150,
        'settings' => [[
            'path' => 'admin.session_idle_timeout',
            'label' => 'Session idle timeout (seconds)',
            'type' => 'text',
            'description' => 'Controlled by ADMIN_SESSION_IDLE_TIMEOUT. Default 7200 seconds; 0 disables idle expiry.',
            'default' => 7200,
            'read_only' => true,
            'sort_order' => 100,
        ], [
            'path' => 'session.lifetime_seconds',
            'label' => 'Session cookie lifetime (seconds)',
            'type' => 'text',
            'description' => 'Controlled by SESSION_LIFETIME_SECONDS. Bounded from 300 to 604800 seconds.',
            'default' => 28800,
            'read_only' => true,
            'sort_order' => 200,
        ], [
            'path' => 'session.samesite',
            'label' => 'Session SameSite policy',
            'type' => 'text',
            'description' => 'Controlled by SESSION_SAMESITE. Accepted values are Lax, Strict and None; invalid values fall back to Lax.',
            'default' => 'Lax',
            'read_only' => true,
            'sort_order' => 300,
        ], [
            'path' => 'security.trusted_proxies',
            'label' => 'Trusted proxy addresses',
            'type' => 'text',
            'description' => 'Controlled by TRUSTED_PROXIES as a comma-separated list of immediate proxy IP addresses.',
            'default' => '',
            'read_only' => true,
            'sort_order' => 400,
        ], [
            'path' => 'rate_limit.mode',
            'label' => 'Login rate-limit mode',
            'type' => 'text',
            'description' => 'Controlled by RATE_LIMIT_MODE. report_only records decisions; enforce returns HTTP 429 after the configured limit.',
            'default' => 'report_only',
            'read_only' => true,
            'sort_order' => 500,
        ], [
            'path' => 'rate_limit.admin_login.max_attempts',
            'label' => 'Login maximum attempts',
            'type' => 'text',
            'description' => 'Controlled by RATE_LIMIT_ADMIN_LOGIN_MAX_ATTEMPTS and bounded from 1 to 100.',
            'default' => 5,
            'read_only' => true,
            'sort_order' => 600,
        ], [
            'path' => 'rate_limit.admin_login.window_seconds',
            'label' => 'Login attempt window (seconds)',
            'type' => 'text',
            'description' => 'Controlled by RATE_LIMIT_ADMIN_LOGIN_WINDOW_SECONDS and bounded from 1 to 86400 seconds.',
            'default' => 300,
            'read_only' => true,
            'sort_order' => 700,
        ]],
    ], [
        'id' => 'routing',
        'label' => 'Routing',
        'description' => 'Administrative routing configuration.',
        'sort_order' => 200,
        'settings' => [[
            'path' => 'admin.base_path',
            'label' => 'Admin base path',
            'type' => 'text',
            'description' => 'Controlled by project configuration and shown read-only.',
            'read_only' => true,
            'sort_order' => 100,
        ]],
    ]],
]];
