<?php
declare(strict_types=1);
namespace Zoosper\UrlRewrite\Api;
use InvalidArgumentException;use PDOException;use Zoosper\Auth\Token\PersonalAccessTokenAuthenticator;use Zoosper\Auth\Token\PersonalAccessTokenPrincipal;use Zoosper\Core\Http\{JsonResponder,Request,Response};use Zoosper\UrlRewrite\Model\UrlRewrite;use Zoosper\UrlRewrite\Repository\UrlRewriteRepository;use Zoosper\UrlRewrite\Service\{RedirectChainInspector,RedirectPolicy};
final readonly class UrlRewriteApiController{
 public function __construct(private JsonResponder $json,private PersonalAccessTokenAuthenticator $auth,private UrlRewriteRepository $rewrites,private RedirectPolicy $policy,private RedirectChainInspector $chains){}
 public function index(Request $r):Response{$p=$this->principal($r,'url_rewrites:read');if($p instanceof Response)return$p;$site=$r->siteContext()?->siteId;if($site===null)return$this->json->error('site_not_found','No active Site exists for this host.',404);return$this->json->success(['url_rewrites'=>array_map($this->row(...),$this->rewrites->allForSite($site))]);}
 public function show(Request $r):Response{$p=$this->principal($r,'url_rewrites:read');if($p instanceof Response)return$p;$x=$this->rewrite($r);return$x===null?$this->json->error('url_rewrite_not_found','URL Rewrite does not exist for this Site.',404):$this->json->success(['url_rewrite'=>$this->row($x)]);}
 public function create(Request $r):Response{return $this->save($r,null);}
 public function update(Request $r):Response{$x=$this->rewrite($r);return$x===null?$this->json->error('url_rewrite_not_found','URL Rewrite does not exist for this Site.',404):$this->save($r,$x);}
 public function disable(Request $r):Response{return$this->status($r,false);}
 public function restore(Request $r):Response{return$this->status($r,true);}
 private function save(Request $r,?UrlRewrite $existing):Response{$p=$this->principal($r,'url_rewrites:write');if($p instanceof Response)return$p;$site=$r->siteContext()?->siteId;if($site===null)return$this->json->error('site_not_found','No active Site exists for this host.',404);$b=$r->json();try{$v=$this->policy->validate((string)($b['request_path']??$existing?->requestPath??''),(string)($b['target_path']??$existing?->targetPath??''),(int)($b['redirect_type']??$existing?->redirectType??301));$this->chains->inspect($site,$v['source'],$v['target']);$id=$this->rewrites->save($existing?->id,$site,$v['source'],$v['target'],$v['type'],(bool)($b['active']??$existing?->isActive??true));}catch(InvalidArgumentException|PDOException $e){return$this->json->error('invalid_url_rewrite',$e->getMessage(),422);}$x=$this->rewrites->findByIdForSite($id,$site);return$this->json->success(['url_rewrite'=>$this->row($x)],$existing===null?201:200);}
 private function status(Request $r,bool $active):Response{$p=$this->principal($r,'url_rewrites:write');if($p instanceof Response)return$p;$x=$this->rewrite($r);if($x===null)return$this->json->error('url_rewrite_not_found','URL Rewrite does not exist for this Site.',404);$this->rewrites->changeStatus($x->id,$x->siteId,$active);return$this->json->success(['url_rewrite'=>$this->row($this->rewrites->findByIdForSite($x->id,$x->siteId))]);}
 private function rewrite(Request $r):?UrlRewrite{$site=$r->siteContext()?->siteId;return$site===null?null:$this->rewrites->findByIdForSite((int)$r->routeParam('id','0'),$site);}
 private function principal(Request $r,string $scope):PersonalAccessTokenPrincipal|Response{$p=$this->auth->authenticate($r->header('authorization'));if($p===null)return$this->json->error('invalid_bearer_token','A valid bearer token is required.',401);if(!$p->allows($scope)||!$p->user->can('settings.manage'))return$this->json->error('insufficient_scope','The bearer token cannot perform this URL Rewrite operation.',403);return$p;}
 private function row(?UrlRewrite $x):array{return$x===null?[]:['id'=>$x->id,'site_id'=>$x->siteId,'request_path'=>'/'.$x->requestPath,'target_path'=>$x->targetPath,'redirect_type'=>$x->redirectType,'active'=>$x->isActive,'entity_type'=>$x->entityType,'entity_id'=>$x->entityId];}
}
