<?php

declare(strict_types=1);

namespace Zoosper\Page\Content;

/**
 * Converts supported Editor.js block JSON into conservative frontend HTML.
 *
 * This renderer deliberately owns the generated markup and escapes all user
 * supplied block text. Templates may render the resulting string as trusted HTML
 * because tags are generated by this class, not accepted directly from the JSON.
 */
final readonly class BlockJsonToHtmlRenderer
{
    /** @param array<string, mixed> $document */
    public function render(array $document): string
    {
        $blocks = is_array($document['blocks'] ?? null) ? $document['blocks'] : [];
        $html = [];

        foreach ($blocks as $block) {
            if (!is_array($block)) {
                continue;
            }

            $type = (string) ($block['type'] ?? '');
            $data = is_array($block['data'] ?? null) ? $block['data'] : [];
            $fragment = match ($type) {
                'paragraph' => $this->paragraph($data),
                'header' => $this->header($data),
                'list' => $this->list($data),
                default => '',
            };

            if ($fragment !== '') {
                $html[] = $fragment;
            }
        }

        return implode("\n", $html);
    }

    /** @param array<string, mixed> $data */
    private function paragraph(array $data): string
    {
        $text = trim((string) ($data['text'] ?? ''));

        return $text === '' ? '' : '<p>' . $this->escape($text) . '</p>';
    }

    /** @param array<string, mixed> $data */
    private function header(array $data): string
    {
        $text = trim((string) ($data['text'] ?? ''));
        $level = in_array((int) ($data['level'] ?? 2), [2, 3, 4], true) ? (int) $data['level'] : 2;

        return $text === '' ? '' : '<h' . $level . '>' . $this->escape($text) . '</h' . $level . '>';
    }

    /** @param array<string, mixed> $data */
    private function list(array $data): string
    {
        $tag = (string) ($data['style'] ?? 'unordered') === 'ordered' ? 'ol' : 'ul';
        $items = is_array($data['items'] ?? null) ? $data['items'] : [];
        $itemsHtml = $this->listItems($items);

        return $itemsHtml === '' ? '' : '<' . $tag . '>' . $itemsHtml . '</' . $tag . '>';
    }

    /** @param array<int, mixed> $items */
    private function listItems(array $items): string
    {
        $html = [];
        foreach ($items as $item) {
            $content = '';
            $nestedHtml = '';

            if (is_string($item)) {
                $content = trim($item);
            } elseif (is_array($item)) {
                $content = trim((string) ($item['content'] ?? ''));
                $nested = is_array($item['items'] ?? null) ? $this->listItems($item['items']) : '';
                $nestedHtml = $nested !== '' ? '<ul>' . $nested . '</ul>' : '';
            } else {
                continue;
            }

            if ($content !== '' || $nestedHtml !== '') {
                $html[] = '<li>' . $this->escape($content) . $nestedHtml . '</li>';
            }
        }

        return implode('', $html);
    }

    private function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
