<?php

declare(strict_types=1);

namespace Zoosper\Page\Content;

use Zoosper\Media\EditorJs\EditorJsImageBlockSanitizer;

/**
 * Converts supported Editor.js block JSON into conservative frontend HTML.
 *
 * This renderer deliberately owns the generated markup and escapes all user
 * supplied block text. Templates may render the resulting string as trusted HTML
 * because tags are generated by this class, not accepted directly from JSON.
 */
final readonly class BlockJsonToHtmlRenderer
{
    public function __construct(private ?EditorJsImageBlockSanitizer $imageSanitizer = null)
    {
    }

    /** @param array<string, mixed> $document */
    public function render(array $document): string
    {
        $blocks = is_array($document['blocks'] ?? null) ? $document['blocks'] : [];
        $html = [];

        foreach ($blocks as $block) {
            if (!is_array($block)) {
                continue;
            }

            $type = (string) ($block['type'] ?? '');
            $data = is_array($block['data'] ?? null) ? $block['data'] : [];
            $fragment = match ($type) {
                'paragraph' => $this->paragraph($data),
                'header' => $this->header($data),
                'list' => $this->list($data),
                'image' => $this->image($data),
                'quote' => $this->quote($data),
                'delimiter' => $this->delimiter(),
                'code' => $this->code($data),
                'table' => $this->table($data),
                'raw' => $this->raw($data),
                default => '',
            };

            if ($fragment !== '') {
                $html[] = $fragment;
            }
        }

        return implode("\n", $html);
    }

    /** @param array<string, mixed> $data */
    private function quote(array $data): string
    {
        $text = trim((string) ($data['text'] ?? ''));
        if ($text === '') {
            return '';
        }

        $caption = trim((string) ($data['caption'] ?? ''));
        $alignment = (string) ($data['alignment'] ?? 'left');
        $alignClass = in_array($alignment, ['center', 'right'], true) ? ' class="cms-quote--' . $alignment . '"' : '';

        $html = '<blockquote' . $alignClass . '><p>' . $this->escape($text) . '</p>';
        if ($caption !== '') {
            $html .= '<cite>' . $this->escape($caption) . '</cite>';
        }
        $html .= '</blockquote>';

        return $html;
    }

    private function delimiter(): string
    {
        return '<hr class="cms-delimiter">';
    }

    /** @param array<string, mixed> $data */
    private function code(array $data): string
    {
        $code = (string) ($data['code'] ?? '');
        if (trim($code) === '') {
            return '';
        }

        return '<pre class="cms-code"><code>' . $this->escape($code) . '</code></pre>';
    }

    /** @param array<string, mixed> $data */
    private function table(array $data): string
    {
        $content = is_array($data['content'] ?? null) ? $data['content'] : [];
        if ($content === []) {
            return '';
        }

        $withHeadings = ($data['withHeadings'] ?? false) === true;
        $html = '<table class="cms-table">';

        foreach ($content as $rowIndex => $row) {
            if (!is_array($row)) {
                continue;
            }

            $html .= '<tr>';
            $isHeadingRow = $withHeadings && $rowIndex === 0;

            foreach ($row as $cell) {
                $cellText = is_scalar($cell) ? trim((string) $cell) : '';
                $tag = $isHeadingRow ? 'th' : 'td';
                $html .= '<' . $tag . '>' . $this->escape($cellText) . '</' . $tag . '>';
            }

            $html .= '</tr>';
        }

        $html .= '</table>';

        return $html;
    }

    /** @param array<string, mixed> $data */
    private function raw(array $data): string
    {
        $html = trim((string) ($data['html'] ?? ''));

        return $html === '' ? '' : $this->escape($html);
    }

    /** @param array<string, mixed> $data */
    private function paragraph(array $data): string
    {
        $text = trim((string) ($data['text'] ?? ''));

        return $text === '' ? '' : '<p>' . $this->escape($text) . '</p>';
    }

    /** @param array<string, mixed> $data */
    private function header(array $data): string
    {
        $text = trim((string) ($data['text'] ?? ''));
        $level = in_array((int) ($data['level'] ?? 2), [2, 3, 4], true) ? (int) $data['level'] : 2;

        return $text === '' ? '' : '<h' . $level . '>' . $this->escape($text) . '</h' . $level . '>';
    }

    /** @param array<string, mixed> $data */
    private function list(array $data): string
    {
        $tag = (string) ($data['style'] ?? 'unordered') === 'ordered' ? 'ol' : 'ul';
        $items = is_array($data['items'] ?? null) ? $data['items'] : [];
        $itemsHtml = $this->listItems($items);

        return $itemsHtml === '' ? '' : '<' . $tag . '>' . $itemsHtml . '</' . $tag . '>';
    }

    /** @param array<string, mixed> $data */
    private function image(array $data): string
    {
        if ($this->imageSanitizer === null) {
            return '';
        }

        $image = $this->imageSanitizer->sanitise($data);
        if ($image === null) {
            return '';
        }

        $classes = ['cms-image'];
        if ($image['withBorder']) {
            $classes[] = 'cms-image--bordered';
        }
        if ($image['withBackground']) {
            $classes[] = 'cms-image--background';
        }
        if ($image['stretched']) {
            $classes[] = 'cms-image--stretched';
        }

        $caption = $image['caption'];
        $html = '<figure class="' . $this->escape(implode(' ', $classes)) . '">'
            . '<img src="' . $this->escape($image['url']) . '" alt="' . $this->escape($caption) . '" loading="lazy">';

        if ($caption !== '') {
            $html .= '<figcaption>' . $this->escape($caption) . '</figcaption>';
        }

        return $html . '</figure>';
    }

    /** @param array<int, mixed> $items */
    private function listItems(array $items): string
    {
        $html = [];
        foreach ($items as $item) {
            $content = '';
            $nestedHtml = '';

            if (is_string($item)) {
                $content = trim($item);
            } elseif (is_array($item)) {
                $content = trim((string) ($item['content'] ?? ''));
                $nested = is_array($item['items'] ?? null) ? $this->listItems($item['items']) : '';
                $nestedHtml = $nested !== '' ? '<ul>' . $nested . '</ul>' : '';
            } else {
                continue;
            }

            if ($content !== '' || $nestedHtml !== '') {
                $html[] = '<li>' . $this->escape($content) . $nestedHtml . '</li>';
            }
        }

        return implode('', $html);
    }

    private function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
